# Generated by Django 3.2.8 on 2021-10-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hire_date',
            field=models.DateField(null=True),
        ),
    ]
